Health-Education-England/hee-cms-platform

- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-administration.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-lks-gallery-and-assets.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-lks.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/groups/lks-author.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/groups/lks-editor.yaml
- repository-data/application/src/main/resources/hcm-content/content/assets/lks.yaml
- repository-data/development/src/main/resources/hcm-config/lks-author.yaml
- repository-data/development/src/main/resources/hcm-config/lks-editor.yaml
- `lks-author` & `lks-editor` user group setup.
- Security domains setup for LKS documents, gallery and assets.
- Additional security domain to restrict users of `lks-author` & `lks-editor` groups to edit documents under `/content/documents/administration` so that it could be managed by Site/System Admin.
> HEE-90: User groups and security domains setup for LKS document workflow

- repository-data/application/src/main/resources/hcm-actions.yaml
Reload `Homepage` resource bundle to fix missing Homepage labels on brCloud Test (& Staging) environments.
As you know `Global` resource bundle has already been reloaded as part of other PRs.
> HEE-159: To reload homepage resource bundle

- repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/patient-and-public-information-minihub-page.yaml
- repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/patient-and-public-information.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations/common/prototypepages/minihub-page.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/workspace.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/MiniHubComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/info/MiniHubComponentInfo.java
- site/components/src/main/java/uk/nhs/hee/web/listeners/PageCreateEventListener.java
- site/components/src/main/resources/META-INF/hst-assembly/overrides/page-event-listeners.xml
- Add MiniHub catalog so that editor can drag the component into page container
- Add MiniHub page prototype so that we can customize the workspace's sitemap generation for created page. We need to create the nested _default_ sitemap item.
- Create demo MiniHub page from Experience Manager which is available under local URL http://localhost:8080/site/patient-and-public-information/copyright
> Configure mini hub to appear in channel manager

- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/formpage-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/guidance-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/listingpage-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
Because the main content of HEE website always take the full maximum width of the page so for all pages in our system should have these 2 wrapper around the main content. We did it on the hee-prototypes project.
```
<div class="nhsuk-width-container">
<main class="nhsuk-main-wrapper" id="maincontent" role="main">
</main>
</div>
```
So I tried to achieve this to setup these wrapper in the base-layout.ftl instead of each page template files.
> Setup nhsuk main content layout wrapper globally in base-layout.ftl

- repository-data/application/src/main/resources/hcm-actions.yaml
- repository-data/application/src/main/resources/hcm-content/content/assets/lks.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/lks.yaml
- repository-data/application/src/main/resources/hcm-content/content/gallery/lks.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/workspace/channel.yaml
- Updated name from `LKS` to `KLS` for document, gallery and asset root folders.
- Moved `repository-data/development/src/main/resources/hcm-content/content/documents/lks.yaml` & `repository-data/development/src/main/resources/hcm-content/content/gallery/lks.yaml` under application repository-data so that document and gallery LKS top level folders are bootstrapped on Test, Staging and Production environments.
**Note:** Haven't included content reloads for `/content/documents/lks, /content/gallery/lks & /content/assets/lks` as it would potentially delete these folders (including child nodes) and so the above name change needs to be applied manually on each environments.
> LKS -> KLS name update

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/QuickLinks.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/link.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/lks.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/action-link.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/back-link.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/content-cards.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/link.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/quick-links.ftl
- Made (Link) `text` field of `link` CompoundType as optional.
- Made `title` & `links` fields of `QuickLinks` CompoundType are optional.
- Amended all `link` compound type based freemarker templates to render links when link text and document/url are available.
> QuickLinks/Link fields (Required/Optional) Amendment

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
Right now the when the guidance is embedded in the MiniHub page, its title has been shown duplicated at both top of the page and below the content list. This PR will hide the one which located under the content list.
> HEE-189: Do not show duplicate guidance title on the mini hub

- repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-richtext-block.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/richTextBlock.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/richTextReference.yaml
- repository-data/development/src/main/resources/hcm-actions.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/RichTextBlock.java
- site/components/src/main/java/uk/nhs/hee/web/beans/RichTextReference.java
- Add new document type RichTextBlock with html field
- Add new compound type RichTextReference which have a link which can reference to RichTextBlock
- In the guidance page's content block, configure so that user can pick RichTextReference from here.
> HEE-196: Add reusable RichText document type

- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/MiniHubComponent.java
- Enhance the way to extract the next previous guidance URLs which support when the MiniHub put into the IA with nested URLS like https://production-hee.onehippo.io/site/knowledge-management/knowledge-management-toolkit
> HEE-210: Enhance guidance navigation when putting MiniHub in IA with nested URLs

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/quick-links.ftl
- when editor does not maintain any data on the QuickLink content then system should not show the white box
> HEE-202: Do now show the white box when without any data

- repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/kls/blogcategories.yaml
This is to essentially to sync up project repo with latest blog categories (which was already migrated to brCloud env [upto Staging as of now] as part of archived blog post migration) to ensure that a future reload of `blogcategories` value-list doesn't wipes out migrated categories from env.
> HEE-174: updated blogcategories value-list with (migrated) archived blog categories included

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/ListingPageComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/ListingPageType.java
- site/components/src/main/java/uk/nhs/hee/web/constants/HeeNodeType.java
Note that when blogs are being sorted on search page (/site/search), it would still use default document last modified date meta field `hippostdpubwf:lastModificationDate` as it is the potential common sort field for all document types.
> HEE-238: Update to render blogs listing by 'hee:publicationDate' field

- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/hometoknowledgestaffredirect.yaml
This revert is to ensure that the redirect doesn't add a trailing question mark. Also, this redirect isn't expected to carry any query strings as of now and need to revisited in the future if such a requirement comes up.
> HEE-248: Query string append revert for home page (/) to knowledge staff (/knowledge-staff) redirect

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogComment.yaml
This is to ensure that the CMS doesn't complains Editors to enter a comment when creating a `blogPost` document.
> HEE-260: Making blog comment fields (author, message & postedDate) optional

- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/ListingPageComponent.java
- site/components/src/main/java/uk/nhs/hee/web/utils/HstUtils.java
- Reverting changes made as part of the PR https://githubcom/Manifesto-Digital/hee-cms-platform/pull/79.
- Updated listing view/template to render documents only if it resolves to a channel page i.e. when the generated URL is not `/pagenotfound` (unless it's a MiniHub Guidance page). Note that this will leave the listing to display fewer results than what's set for `Page Size` in the corresponding ListingPage. In order to avoid this situation, Editors should be advised to not to publish documents which aren't ready to be added to the channel yet (unless it's a MiniHub Guidance document).
- Implemented a fix to render MiniHub Guidance pages with correct URLs.
> HEE-252: Fix to render MininHub Guidance pages with correct URLs

- repository-data/application/src/main/resources/hcm-actions.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/searchBank.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/listing.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/kls/searchbankkeyterms.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/kls/searchbankproviders.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/kls/searchbanktopics.yaml
- repository-data/development/src/main/resources/hcm-actions.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/search-bank.yaml
- repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/search-bank-contentpage.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/casestudylisting-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchbanklisting-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/BlogPost.java
- site/components/src/main/java/uk/nhs/hee/web/beans/SearchBank.java
- site/components/src/main/java/uk/nhs/hee/web/components/CategoryBasedListingPageComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/EventListingPageComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/ListingPageComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/ListingPageType.java
- site/components/src/main/java/uk/nhs/hee/web/components/SearchBankListingPageComponent.java
- site/components/src/main/java/uk/nhs/hee/web/constants/HeeNodeType.java
- site/components/src/main/java/uk/nhs/hee/web/repository/HEEField.java
- site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
- SearchBank CMS fields alignment with migration JSON data. The following field amendments have been made:
- `description` field has been removed.
- `details` field has been removed.
- `categories` field has been replaced with `topics` field.
- Amended `provider` field to use `/content/documents/administration/valuelists/kls/searchbankproivders` value-list (which was previously using a Text[Area] field).
- `keyTerms` field has been added which in turn uses `/content/documents/administration/valuelists/kls/searchbankkeyterms` value-list.
- Separate `Search Bank Listing Page` component build for SearchBank Listing.
- SearchBank listing page/FE update based on CMS field amendments.
The first part of the HEE-271 ticket i.e. Search Bank data migration/import has been dealt separately as part …
> HEE-271: SearchBank CMS fields alignment with migration data

- repository-data/application/src/main/resources/hcm-actions.yaml
- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/kfhtolksredirects.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml
- Prod virtual host setup for `kfh.libraryservices.nhs.uk`.
- Rewrite rule to perform `kfh.libraryservices.nhs.uk` domain level [301] redirect to `library.hee.nhs.uk`.
Note that the following domain level redirect has been added part of existing rewrite rule document `/content/urlrewriter/kls/kfhtolksredirects` and as the first rule in order to ensure that it is processed first before the other old to new website redirects are processed.
```
<rule>
<name>kfh.libraryservices.nhs.uk to library.hee.nhs.uk Domain Level Redirect</name>
<note>This redirect added here intentionally in order to ensure that the domain level redirect happens first before any of the following redirects are processed</note>
<condition name="host" operator="equal">kfh.libraryservices.nhs.uk</condition> …
```
> HEE-281: kfh.libraryservices.nhs.uk domain level redirect setup

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/MiniHub.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/documenttypes.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
- MiniHub `Guidance Pages` field caption has beeb updated to `Standard Content Pages`.
- `Guidance` component label has been updated to `Standard Content Page`.
- `Guidance` value-list item [used on ListingPage `Document Types (Applicable for Search Listing Type)` field] has been updated to `Standard Content Page`.
> HEE-241: Guidance reference updates

- repository-data/site/src/main/resources/hcm-config/hst/configurations/default/catalog.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/blogpage-main.ftl
Note that existing comments on the blog posts will still be displayed. Hope this is OK ?
Since we have commented out `comment` component:
```
<@hst.include ref="comment"/>
```
warning messages similar to the following would be logged:
```
[INFO] [talledLocalContainer] 03.11.2021 12:34:09 WARN  http-nio-8080-exec-3 [AggregationValve.logPossibleWaste:599] POSSIBLE WASTE DETECTED in request 'Request{ method='GET', scheme='http', host='localhost:8080', requestURI='/site/expert-searching', queryString='null'}' : Component '/hst:hee/hst:configurations/lks/hst:workspace/hst:pages/expert-searching-blog-page/main/comment' gets rendered but never adds anything to the response. Its renderer 'classpath:vbox.ftl' is never flushed to a parent component. This might be waste you are not aware of. If it …
```
> HEE-233: Switching off the ability to add comments to blog posts

- repository-data/application/src/main/resources/hcm-config/configuration/userroles/hee.site.viewer.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/userroles/xm.cms.user.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-brcloud/io.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/tst-brcloud/io.yaml
- site/webapp/src/main/webapp/WEB-INF/hst-config.properties
- Added `hee.site.viewer` userrole to use it for delivery-tier authentication.
- Updated `xm.cms.user` userrole to implicitly include `hee.site.viewer` userrole for all CMS users.
- Enabled authentication for dental channel for all environment virtual hosts.
- Configured delivery-tier `RepositoryAuthenticationProvider` to filter out roles prefixed with `hee.` for authentication (`site/webapp/src/main/webapp/WEB-INF/hst-config.properties`):
```
security.authentication.included.userrole.prefix = hee.
```
Note that the `login` sitemap protocol needs to be changed to `http` for local development: 
```
/hst:hee/hst:configurations/hst:default/hst:sitemap/login/@hst:scheme=http
```
> NWPS-765: Delivery-tier authentication setup for dental channel

- repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-brcloud/io.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/tst-brcloud/io.yaml
Have set up both `X-Frame-Options: SAMEORIGIN` as well as `Content-Security-Policy: frame-ancestors 'self'` response headers on all HST virtual hosts to fix clickjacking vulnerability.
> NWPS-416: Clickjacking vulnerability fix

- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml
Including Clickjacking vulnerability fix response headers (`Content-Security-Policy: frame-ancestors 'self'` & `X-Frame-Options: SAMEORIGIN`) explicitly on prod dental domain (`dental.hee.nhs.uk`) mount [as inherited response headers from `/hst:hee/hst:hosts/prd-brcloud/uk` are lost during `hst:responseheaders` property override at the mount level].
> NWPS-416: Clickjacking vulnerability fix response headers for prod dental domain

- .github/workflows/cicd-release.yml
- .github/workflows/cicd.yml
- conf/context-dev.xml
- pom.xml
- repository-data/application/src/main/resources/hcm-config/configuration/update/registry/AddModerationStatusToBlogPostDocuments.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/update/registry/UpdateBlogCommentFormContainerComponentsWithBlogPostModerationComponentConfig.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/eforms/form.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogComment.yaml
- repository-data/development/src/main/resources/hcm-actions.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/forms.yaml
- repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/expert-searching-blog-page.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations/default/catalog.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/blogpage-main.ftl
- site/components/pom.xml
- site/components/src/main/java/uk/nhs/hee/web/beans/BlogComment.java
- site/components/src/main/java/uk/nhs/hee/web/components/BlogPostComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/eforms/NoAutoDetectFormComponent.java
- site/components/src/main/java/uk/nhs/hee/web/eforms/hst/behaviors/BlogPostCommentMailFormDataBehavior.java
- site/webapp/src/main/java/uk/nhs/hee/web/eform/behaviors/StoreBlogCommentBehavior.java
- `Moderated ?` field (`hee:moderated`) [defaulting to `false`] has been introduced on `hee:blogComment` CompoundType in order to record comment moderation status.
- `uk.nhs.hee.web.components.BlogPostComponent` has been updated to add only moderated comments to the model.
- `blog-comment-form` (catalog) component has been updated to use `uk.nhs.hee.web.components.eforms.NoAutoDetectFormComponent` from `com.onehippo.cms7.eforms.hst.components.AutoDetectFormComponent` in order to avoid auto detecting and adding default behaviours.
- An extension of `com.onehippo.cms7.eforms.hst.behaviors.MailFormDataBehavior` has been implemented `uk.nhs.hee.web.eforms.hst.behaviors.BlogPostCommentMailFormDataBehavior` for blog-comment-form to replace `##BLOG_POST_DOCUMENT##` placeholder with blog post …
> NWPS-233: Blog moderation implementation

- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/hometodentaltraineerecruitment.yaml
- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/searchtosearchresultsredirect.yaml
- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/hometoknowledgestaffredirect.yaml
- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/kfhtolksredirects.yaml
- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/searchtosearchresultsredirect.yaml
- Removal of `knowledge-staff` redirects from 'KFHToLKSRedirects' rewrite rule.
- Simplifying and optimising KLS and dental channel home & search rewrite rules for internal & external redirects.
- Converting KLS and dental channel home redirects from `301` (permanent) to `302` (temporary).
*Note* that the rewrite rule fixes included in this PR has already been applied to prod and the PR is essentially to keep the repository in sync. Thanks!
> NWPS-805 & NWPS-815: Rewrite rule fixes

- repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-details-document.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/details.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/detailsReference.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
- repository-data/development/src/main/resources/hcm-actions.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/home.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/components.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/details.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/homepage-main.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/Details.java
- site/components/src/main/java/uk/nhs/hee/web/beans/DetailsReference.java
https://hee-tis.atlassian.net/browse/NWPS-412 
I have created:
- a new Details document type
- a new Details (reusable) compound type
- added Details (reusable) compound type to the list of allowed content blocks for the guidance pages and home page
- added template query for the Details document type that is used to restrict the content that can be created inside a folder. 
- added an example of Details document type and updated the the [Home Page](http://localhost:8080/site/knowledge-staff) and [Guidance Page](http://localhost:8080/site/copyright) to display it.
> Add details document type and details (reusable) compound type.

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/tabs.ftl
Note that the fix renders mobile version of tabs component in mobile view (rather than desktop version), but the misalignment of the tabs will still occur in desktop view if the tab title is too long and it would be fixed as part of css/js separation work which @dawntaroni is currently working on.
> NWPS-936: Rendering tabs component with mobile version

- cms/src/main/resources/org/hippoecm/frontend/plugins/yui/upload/validation/DefaultUploadValidationService.properties
- repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms.yaml
- Including support for the following file extensions for Assets:
- *.pdf
- *.doc
- *.docx
- *.ppt
- *.pptx
- *.xls
- *.xlsx
- *.odt
- *.fodt
- *.odp
- *.fodp
- *.ods
- *.fods
- *.odg
- *.fodg
- *.mrc
- *.txt
- Removed support for `SVG` for Images.
- Customised "file.validation.extension.disallowed" message (via `cms/src/main/resources/org/hippoecm/frontend/plugins/yui/upload/validation/DefaultUploadValidationService.properties`) to append the upload error msg with additional details requested by Andy.
> NWPS-996: Configure allowed file extensions for "assetValidationService"

- repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live-redirect.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live-redirect/uk.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live.yaml
- repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live/uk.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
- Separated out live site vhosts under `prd-live`.
- Separated out live site redirect vhosts under `prd-live-redirect`.
- Amended `repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl` to render `<title>` tag using corresponding (channel) page title and fallback to document title if empty.
- Added title for page not found page.
> NWPS-943: Fix for "channel with duplicate id" error

- .github/workflows/cicd-release.yml
- .github/workflows/cicd.yml
- README.md
- conf/hee-platform.properties
- conf/log4j2-dev.xml
- conf/log4j2-dist.xml
- pom.xml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/forms.yaml
**Verification:**
- On the CMS side, have verified Content management [`content`], Channel & page management [`Experience manager`], User management [`Setup -> brXM User management`], Groovy scripts [`Setup -> System -> Update editor`].
- On the Site side, have verified Channel virtual hosts and their pages.
- Have also verified Console and Repository applications.
*Log Target* feature support:
- Updated CICD workflow files to deploy `conf/context.xml` file additionally as Java System Properties (containing `groovy.persist.logs.supported=true` property) to enable `Log Target` feature for updater (groovy) scripts for non-local environments.
- Added `org.onehippo.repository.update.UpdaterExecutionReport` INFO logger to log updater (groovy) script outputs on `Log Files`.
> NWPS-970: brXM upgrade from 14.7.3 to 14.7.8

- repository-data/application/src/main/resources/hcm-config/configuration/modules/htmlprocessor.yaml
Removed the following tags (and its attributes) from RichText editor server-side whitelisting config (`/hippo:configuration/hippo:modules/htmlprocessor/hippo:moduleconfig/richtext`) so as to filter them out:
- embed [allowscriptaccess, height, src, type, width]
- iframe [align, allow, allowfullscreen, class, frameborder, height, id, longdesc,
name, scrolling, src, style, title, width]
- html
- object [align, class, data, height, id, style, title, type, width]
- param [class, name, value, style]
- select [class, multiple, name, size, style]
- option [class, selected, style, value]
- textarea [class, cols, name, rows, style]
`script` and `input` tags aren't whitelisted already and so no action is required. Thanks!
> NWPS-997: Removal of unsupported tags from CKEditor server-side whitelisting so as to filter them out.

- repository-data/application/src/main/resources/hcm-config/namespaces/hippostd/html.yaml
Disabling CKEditor automatic [Content Filtering](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) feature as we have decided/implemented to go with [brXM HTML clean-up mechanism](https://xmdocumentation.bloomreach.com/library/concepts/document-types/html-fields/html-cleaning.html#scroll_server-side) as part of `NWPS-997` ticket to handle it at the server-side. Thanks!
> NWPS-1109: Disabling CKEditor automatic content filtering filter 

- repository-data/application/src/main/resources/hcm-config/configuration/update/registry/SuppressWasteMessageForBlogCommentContainerComponent.yaml
- repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/expert-searching-blog-page.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations/common/prototypepages/blog-page.yaml
- repository-data/site/src/main/resources/hcm-config/hst/configurations/default/catalog.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/blogpage-main.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/BlogPostComponent.java
- Hides `Blog Comment Form` component from the Experience Manage component catalog so that Editor wouldn't be able to add it to the `Comment Form` container.
- Doesn't render blog comment form and existing comments on `Blog post` pages.
- `SuppressWasteMessageForBlogCommentContainerComponent` updater script which adds `hst:suppresswastemessage = true` property to all `comment` `hst:containercomponent` nodes in order to suppress logging `comment` component waste message [similar to the following]:
```[INFO] [talledLocalContainer] 29.09.2022 15:57:56 WARN  http-nio-8080-exec-6 [AggregationValve.logPossibleWaste:609] POSSIBLE WASTE DETECTED in request 'Request{ method='GET', scheme='http', host='localhost:8080', requestURI='/site/_cmsinternal/expert-searching', queryString='null'}' : …
```
> NWPS-1125: Disabling blog comment feature

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/Department.java
- The existing Department `description` data from `repository-data/development` aren't removed yet as they would need to be migrated to the new `Contact card` DocumentType once it is created as part of `NWPS-1090`.
- Similarly, the logic for rendering Department `description` field has been removed from `repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl` and will be moved to freemarker template of `Contact card` that would be built as part of `NWPS-1090`.
Thanks!
> NWPS-1089: Removal of 'description' field from 'Department' DocumentType

- repository-data/webfiles/src/main/resources/site/css/cms-request.css
- repository-data/webfiles/src/main/resources/site/css/hee_custom_backend.css
- repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-top.ftl
Also, added a workaround to remove additional wrapper div's introduced by 'multi-org-logo' container for non channel manager preview requests.
> NWPS-1003: Moving 'multi-org-logo' container specific CSS classes onto 'cms-request.css' for consistency

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/details.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/expanderPanel.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hippostd/html.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/case-studies.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/landing-pages.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/reports.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/search-bank.yaml
Includes cherry-picked a8f1f968dbd6188c58873002cf7d603a34ad90a9 commit as well (to close opened documents).
We can close https://github.com/Health-Education-England/hee-cms-platform/pull/285 if we are happy with this.
> NWPS-1184: Removal of 'Table' button from RTE globally except Details, Expander, Table & Tabs document types

- repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
Removing `/content/documents/lks/common/logos/health-education-england` logo from the repository as well as from its associated logo groups.
> NWPS-1003: [tidy-up] 'Health Education England' logo data tidyup

- cms/src/main/java/uk/nhs/hee/web/validation/validator/PhoneNumberValidator.java
- repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/update/registry/RemoveUKCountryCodeFromPhoneNumbers.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/person.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-contact.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/utils/phone-number-util.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/Person.java
- Person
- Changed `departmentName` & `bio` fields to `view` only mode.
- Updated `departmentName` & `bio` field captions to include ` (This field is being removed)` suffix.
- Included an optional `department` link picker field right below the existing `departmentName` field.
- Updated person contact freemarker template to render `department`/`departmentName` based on availability.
- Department
- Changed `description` field to `view` only mode.
- Updated `description` field caption to include ` (This field is being removed)` suffix.
- Person/Department
- Amended phone number validation as per the latest requirement.
- Changed `phoneNumber` field length to `13`.
- Changed `phoneExtension` field length to `5`.
- Added numeric validation for `phoneExtension` field.
- Updated …
> NWPS-1088 & NWPS-1089: Latest person/department updates

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/author-cards.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/BlogPost.java
- site/components/src/main/java/uk/nhs/hee/web/beans/News.java
- site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java
- Added `Hide Author contact details` optional check box field (defaulting to `unchecked`) right below the `Authors` field on the `Blog post`, `News` and `Publication landing page` documents.
- Updated Author card-related freemarker templates to not render email & work address if `Hide Author contact details` is `checked`.
> [NWPS-1331] Impl. of 'Hide Author contact details' checkbox toggle for Blog post, News and Publication landing pages

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
- Removed default `Anchor links` content block from the `Main content objects` field.
- `Anchor links` dev content block content tidy up.
- Removed document format rendering from `Alternative versions` and `Languages` sidebar cards.
**Note** that the `Main content objects` field default `Anchor links` content block (`/hippo:namespaces/hee/report/hipposysedit:prototypes/hipposysedit:prototype/hee:contentBlocks
`) should manually be deleted from the environment to which this change will be deployed:
> [NWPS-1340]: Publication page document type and freemarker updates

- repository-data/application/src/main/resources/hcm-actions.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/documenttypes.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/listing-pages.yaml
- site/components/src/main/java/uk/nhs/hee/web/components/SearchResultsComponent.java
- Updated `/content/documents/administration/valuelists/documenttypes` value-list to include `Publication landing` (`hee:publicationLandingPage`) document type so as to include it for `Search Results` listing page document. Also, updated `value` field of `/content/documents/administration/valuelists/documenttypes` to follow the sentence case naming convention.
- Included reloading action for `/content/documents/administration/valuelists/documenttypes` value-list via `repository-data/application/src/main/resources/hcm-actions.yaml`
> [NWPS-1144] Inclusion of Publication landing pages in search results

- repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-contact-card-description.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/contactCardWithDescription.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/contactCardWithDescriptionReference.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
- repository-data/application/src/main/resources/hcm-content/content/documents/lks/contact-card-summary-one.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/components.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/contact-card-with-description.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/contact-card.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-contact.ftl
- site/components/src/main/java/uk/nhs/hee/web/beans/ContactCardWithDescription.java
- site/components/src/main/java/uk/nhs/hee/web/beans/ContactCardWithDescriptionReference.java
Rename old contact card to Card - Contact (Old)
Added new contact card Card - Contact which contains description field and selected contact
Modified Blog post, Home, News article and Standard content pages by removing ability to add "Contact - Card (Old)" types and only allow "Contact - Card" in RHS for Blog, News article and Standard content
Note: All templates still display previously created "Contact - Card (Old)" content, if present, but will not allow new instances to be added (must be "Contact - Card" ony, where applicable)
> [NWPS-1090] Update contact component and allow addition of description

- cms/src/main/java/uk/nhs/hee/web/repository/documentworkflow/DocumentWorkflowImplWithoutCopyOperation.java
- cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueWebPublicationsValidator.java
- cms/src/test/java/uk/nhs/hee/web/repository/documentworkflow/DocumentWorkflowImplWithoutCopyOperationTest.java
- cms/src/test/java/uk/nhs/hee/web/validation/validator/UniqueWebPublicationsValidatorTest.java
- repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/workflows/default.yaml
- `UniqueWebPublicationsValidator` has been updated to raise a duplicate `Publication page` error in case the same `Publication page` document has been associated with a `Publication landing page` document multiple times (via `Publication pages` field).
- `/hippo:configuration/hippo:workflows/default/publicationLandingPageHandle` workflow has been added for `Publication landing page` document type in order to remove the `Copy...` operation so as to restrict content editors from copying `Publication landing page` documents.
> [NWPS-1346] Publication landing page validator and workflow updates

- cms/pom.xml
- cms/src/main/resources/ckeditor/custom_styles.js
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/AfterForm.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/Inset.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/StatementBlock.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/banner.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/blockLinks.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/details.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/expanderPanel.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/mediaEmbed.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/navMap.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/newsletterSubscribeForm.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/richTextBlock.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/statementCard.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/tabPanel.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/table.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/warningCallout.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hippostd/html.yaml
- Custom `styleSet` impl. for CKEditor to remove `Heading 1` from `Styles` dropdown.
- Reverting `forcePasteAsPlainText=true` for `hippostd:html` and `hee:richTextBlock` document types.
> [NWPS-1292] CKEditor enhancements

- repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/listing.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/ListingPageComponent.java
Please can you review this as there are a few changes;-
- Removed the check for pageNotFound within the template - this was reducing the number of candidates that could be displayed
- Added that check into the ListingComponent along with checks for content type and whether content was being referenced by a mini-hub
- Calculate the URL in the ListingComponent class and pass it to the template (as a property on the beans that are being selected as candidates for display) to stop it being recalculated in the template
- changed the display of total results to take into account "1 result" and "x results"
> [NWPS-1257] Search now correctly finding only content on published pages

- cms-dependencies/pom.xml
- repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
This branch includes the advanced search plugin and has been configured as follows;-
- Only the "hee" namespace is available to be searched (which means that we don't see URL rewrites, for example)
- A title filter (using the hee:title attribute) has been configured as example of a search filter. This can easily be removed by reversing the instructions found here: https://xmdocumentation.bloomreach.com/library/enterprise/enterprise-features/advanced-search/custom-search-filter.html
See the video on ticket NWPS-1128 for more information abut how these filters and search options can be used by an editorial user
THIS CAN BE MERGED AS LONG AS IT IS ONLY TARGETTED AT STAGING FOR TESTING PURPOSES
> [NWPS-1128] Advanced search plugin added

- cms-dependencies/pom.xml
- essentials/src/main/resources/taggingPlugin.xml
- repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/digital-transformation/digital-academy.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/a-to-z-test-content.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/cookies.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/landing-pages.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
- site/components/src/main/java/uk/nhs/hee/web/beans/Guidance.java
Please review this.
Applied tagging only for standard content pages and it can be extended for other content types if required by content editors
It appears the language translations (de,en,es,fr,nl,zh) in resourcebundle are default for standard hippostd namespace. We can raise a ticket to remove all except en. /hippo:configuration/hippo:translations/hippo:types
> [NWPS-1127] Tagging plugin for standard content pages

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/rightHandImageReference.yaml
Make the right-hand image content block mandatory so it cannot be left blank
> NWPS-1434-BE-Image-Content-block-needs-to-be-mandatory

- repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
Changing the output format to `HTML` for `page-meta-data.ftl` in order to auto escape entities (e.g. `&`, etc) to workaround `The entity name must immediately follow the '&' in the entity reference` error contributed by `<@hst.headContribution...>...</@hst.headContribution>`
> [Housekeeping] Fix for `The entity name must immediately follow the '&' in the entity reference`

- repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
Change 'Publication' to 'Publication name' in the components in experience pages
> NWPS-1597-BE-Publication-page-Change-name-display-in-Experience-manager

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/assetResource.yaml
Link picker configuration to choose only assets for the `assetData` field of `assetResource` compound type:
> [NWPS-1374] Link picker configuration update for `assetData` field of `assetResource` compound type

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/featuredContentReference.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
- repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
- site/components/src/main/java/uk/nhs/hee/web/components/BlogPostComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/GuidanceComponent.java
- site/components/src/main/java/uk/nhs/hee/web/components/NewsComponent.java
-Add Featured Content Block into SCP, Blogs, News Article Pages main content blocks
-Add the validation that if a featured content block is added, a featured content type needs to be selected
> NWPS-1617-be-featured-content-display-on-other-pages-as-movable-blocks

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
- Fixed the `Other formats` section on the publication landing page to not display if the `Other formats email` field is empty.
- Updated `webPublications` field name for consistency.
- Removed unused `Anchor links` content block support from the publication single page.
> [NWPS-1658] Publication landing and single page fixes

- repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
Name of page type changed to "[Collection] Publications" to reflect new approach to naming of collections
> [NWPS-1679] Rename of publication listing to refer to collection

- repository-data/application/src/main/resources/hcm-config/configuration/update/registry/TaxonomyMigrationForPublicationLandingPage.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
**Manual steps:**
- Post-deployment, execute the `TaxonomyMigrationForPublicationLandingPage` updater (groovy) script to migrate the existing value-list-based property values into taxonomy-based values. Post-execution, check for warning messages similar to the following on the script log and migrate them manually:
```
WARN 2023-08-21 19:30:48 MANUAL: Failed to migrate 'hee:publicationType = [policy_strategy]' for '/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]'. Please migrate manually
```
- The `hippofacnav:facets` property on `publicationfacets` node should be updated to `['hee:globalTaxonomyPublicationTypes', 'hee:globalTaxonomyHealthcareTopics', …
> [NWPS-1678] Publication landing page taxonomy migration

- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
Supersedes #513 - Created the PR by cherry-picking 1b81d65c2f8833e230e197d146687e257860f588 commit, thanks
> [NWPS-1613] Removing the double space between `PDF,` and `large` in the `Other formats` section

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
Just observed the following error when accessing an SCP page and so made this PR to quickly fix it:
```
[WARNING] [talledLocalContainer] %d{HH:mm:ss} WARN  [HstFreemarkerServlet] The following has evaluated to null or missing:
[INFO] [talledLocalContainer] ==> guidanceDetail  [in template "webfile:/freemarker/hee/macros/guidance-content.ftl" at line 30, column 27]
[INFO] [talledLocalContainer]
[INFO] [talledLocalContainer] ----
[INFO] [talledLocalContainer] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: …
```
> [NWPS-1575] Fixing Guidance (SCP) freemarker template

- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
In publication page, 'Alternative version' section, it needs to show the titles provided by the user, not the file name.
> NWPS-1699-Publication-Alternative-versions

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/google-map.ftl
AddUpdate the Freemarker template for the component, to include the new aria-label attribute.
> NWPS-1665-FE-Title-tag-Tags-for-google-map-for-accessibility

- repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammePage.yaml
- repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-programmes-pages.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
Adds support for `details`, `expander`, `google map`, `table`, `table expander` and `tabs` content blocks on the Training programme page overview section.
> [NWPS-1692] Supporting additional content blocks for the overview section of training programme page

- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/landingPage-main.ftl
The fix is essentially to remove the additional bottom space for `pagenotfound` page (which is now been configured to use the landing page document for rendering) when it doesn't contain any main content blocks.
> [NWPS-841] Fix to remove additional bottom space on the main section of the landing page

- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/website-testing/redirecttospecialtylandingpage.yaml
- Keeping the `draft` version of `/content/urlrewriter/website-testing/redirecttospecialtylandingpage` in sync.
> [NWPS-1771] Content bootstrapping error fixes

- repository-data/application/src/main/resources/hcm-config/configuration/update/registry/AddNewsTypeTaxonomyPropertyToNewsFacets.yaml
**Manual steps:** Execute `AddNewsTypeTaxonomyPropertyToNewsFacets` updater script post-deployment to update `newsfacets` facet node for all channels to include `hee:globalTaxonomyNewsType__with_ancestors` taxonomy property.
> [NWPS-1837] Updater script to update 'newsfacets' facet nodes to include NewsType taxonomy property

- repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/personspecification2024redirects.yaml
**Note that** when we are ready to release this PR, we will need to advise the content team on the release date so that they can advise the stakeholders accordingly. In case stakeholders aren't ready (for any reason) for the redirects to be deployed to prod, I guess we can still deploy, but unpublish the `/content/urlrewriter/medical/personspecification2024redirects` rule post-deployment, thanks.
> [NWPS-1834] Person specification 2024 redirect build for medical (live domain)

- repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/searchresults.yaml
- repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
- Included additional `invalidSearchTerms` for search results to return `400 (Bad request)` for the issue described in the ticket. We can look to remove this temporary solution later once the permanent solution of adding canonical URLs to pages works.
- Included canonical URLs for all pages.
- Included `noindex` `robots` meta tag for listing/collection pages to instruct crawlers not to index them.
> [NWPS-1502] Search engine optimisation for search results and listing/collection page

- repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
Added `aria-hidden="true"` to file icon title element (`<div class="hee-publication-doc__icon__title" aria-hidden="true">...</div>`) to instruct screen readers to ignore reading out the element, thanks
> [NWPS-1784] Publication landing page documents file icon accessibility improvement

- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-dental-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-digital-transformation-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-feedback-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-kls-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-lks-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-medical-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-website-testing-media-embed.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/domains/content-wte-alpha-media-embed.yaml
Make change in the configuration, to specify the groups that have 'readonly' permissions to  media-embed folders
> NWPS-1848-Production-log-issue-Failed-to-transform-element

- .github/workflows/cicd-release.yml
- .github/workflows/cicd.yml
- cms-dependencies/pom.xml
- cms/src/main/java/uk/nhs/hee/web/repository/scheduling/NextReviewDateNotification.java
- cms/src/main/java/uk/nhs/hee/web/utils/DocumentUtils.java
- cms/src/main/java/uk/nhs/hee/web/utils/MailUtils.java
- cms/src/main/java/uk/nhs/hee/web/utils/StringUtils.java
- pom.xml
- repository-data/application/src/main/resources/hcm-config/configuration/modules/scheduler.yaml
- repository-data/application/src/main/resources/hcm-config/configuration/update/queue/DisableNextReviewDateNotificationJobOnNonProdEnvironments.yaml
- A custom repository job `/hippo:configuration/hippo:modules/scheduler/hippo:moduleconfig/custom/NextReviewDateNotification` has been added to search for page documents which require reviewing in the `next 14 - 21 days` i.e. page documents (like `Standard content page`, `Blog post`, etc) whose `hee:pageLastNextReview/@hee:nextReviewed` date falls between the next `14 - 21 days`.
- The repository job `NextReviewDateNotification` has been scheduled to run `weekly on Friday morning at 4`.
- Page document types which needs to be searched for the next reviewed date and email notification settings have been configured under `NextReviewDateNotification` job (as `hipposched:attributeNames` and `hipposched:attributeValues` properties).
- CI/CD pipelines i.e. Github workflow jobs have been …
> [NWPS-1787] NextReviewDateNotification repository job build

- repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
Modify the freemarker tamplate to add alt text and meet the accessibility requirements
>  NWPS-1883-accessibility-author-card-images-should-have-alt-text
