Health-Education-England/hee-cms-platform

README.md
I had an issue setting up, so worth documenting this.
=> adds instructions around brXM accounts

repository-data/application/src/main/resources/hcm-config/hst/hosts/prd-brcloud.yaml, repository-data/application/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml, repository-data/application/src/main/resources/hcm-config/hst/hosts/stg-brcloud.yaml, repository-data/application/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml, repository-data/application/src/main/resources/hcm-config/hst/hosts/tst-brcloud.yaml, repository-data/application/src/main/resources/hcm-config/hst/hosts/tst-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/tst-brcloud.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/tst-brcloud/io.yaml
=> Virtual host group setup for brCoud test, staging and production env

repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd, repository-data/application/src/main/resources/hcm-config/namespaces/hee/YellowAlertBlock.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/guidance-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/yellow-alert-block.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/YellowAlertBlock.java
Adds the yellow alert component
Changes template logic to use switch for readablility
https://manifesto.atlassian.net/browse/HEE-104
=> Yellow alert component

repository-data/webfiles/src/main/resources/site/freemarker/hee/eforms/eforms-field-renderer.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/eforms/eforms.ftl
Move field hint to be right below field label
Set field error id on `aria-describedby` only when there is error message
=> Enhancement on the form template layout

repository-data/application/src/main/resources/hcm-config/namespaces/hee/MiniHub.yaml, repository-data/development/src/main/resources/hcm-actions.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/minihubs.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/MiniHub.java
To resolve this issue https://github.com/Manifesto-Digital/hee-cms-platform/issues/32
=> Mini-hub title to display parent page as sub-heading

repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/channel/channelinfo.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/workspace/channel.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl, site/components/src/main/java/uk/nhs/hee/web/channels/WebsiteInfo.java
- Setup GTM Configuration script and non-script code with the GTM Container ID can be configured by the webmaster by update Channel configuration properties.
=> HEE-87: Setup GTM configuration

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml, repository-data/development/src/main/resources/hcm-actions.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
Add `hee:richTextReference` compound type to the blog page content blocks field.
=> HEE-211: Add reusable rich text block to blog content type

repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/pages/blogpost.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl, site/components/src/main/java/uk/nhs/hee/web/components/BlogPostComponent.java, site/webapp/src/main/java/uk/nhs/hee/web/eform/behaviors/StoreBlogCommentBehavior.java
- Updated `/hst:hst/hst:configurations/lks/hst:pages/blogpost` page configuration to reflect the latest blog post prototype page configuration.
- Extended blog comment feature for archived blog posts.
=> Archived blog posts page configuration and comment feature update

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl, site/components/src/main/java/uk/nhs/hee/web/components/CategoryBasedListingPageComponent.java, site/components/src/main/java/uk/nhs/hee/web/components/ListingPageComponent.java, site/components/src/main/java/uk/nhs/hee/web/components/ListingPageType.java, site/components/src/main/java/uk/nhs/hee/web/components/SearchResultsComponent.java
Also, `Sort by Date` dropdown has been removed from Search Results page as agreed with @MattBrooksManifesto.
=> HEE-256: Boost weight of document hit by 'hee:title' field

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/kfhtolksredirects.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/searchtosearchresultsredirect.yaml
Note that in order for these redirects to work HEE will need to setup a domain level redirect from the old address (https://kfh.libraryservices.nhs.uk/) to the new one (https://library.hee.nhs.uk/).
=> HEE-274: KLS live site redirects

repository-data/application/src/main/resources/hcm-config/configuration/domains/content-medical-assets-and-gallery-readwrite.yaml, repository-data/application/src/main/resources/hcm-config/configuration/domains/content-medical.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/medical-author.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/medical-editor.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/medical-reader.yaml, repository-data/application/src/main/resources/hcm-content/content/assets/medical.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/medical.yaml, repository-data/application/src/main/resources/hcm-content/content/gallery/medical.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/medical/home.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/components.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace/channel.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/tst-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/medical/workspace/channel/channelinfo.yaml, repository-data/site/src/main/resources/hcm-content/hst/sites/medical.yaml
Added a new channel and host config for medical.hee.nhs.uk.
=> New medical education channel

repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/lks/searchbankproviders.yaml
Hi @smanivasag - can you review this please. Note. I've manually updated this key on the various environments.
=> update searchbankprov key imperialcollege

repository-data/application/src/main/resources/hcm-config/namespaces/hee/QuickLinks.yaml
Hi @smanivasag - can you please review this. I wasn't sure if we needed to do anything with hcm actions.
=> make title field mandatory for quicklinks

site/components/src/main/java/uk/nhs/hee/web/beans/Tabs.java
forgot to remove the unused import for random prefix
=> remove unused import

repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml, repository-data/development/src/main/resources/hcm-actions.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/home.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/homepage-main.ftl
Included the following CompoundTypes on HomePage:
- Anchor links [hee:anchorLinks]
- Block links (reusable) [hee:blockLinksReference]
- Contact [hee:contact]
- Rich text (reusable) [hee:richTextReference]
- Tabs (reusable) [hee:tabsReference]
=> HEE-326: Additional blocks to HomePage

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
Hi Selva - should be ready for review.
=> add body-l class to guidance summary

pom.xml
More info are available in https://arstechnica.com/information-technology/2021/12/minecraft-and-other-apps-face-serious-threat-from-new-code-execution-bug, https://nvd.nist.gov/vuln/detail/CVE-2021-44228 and https://issues.apache.org/jira/browse/LOG4J2-2109
=> Bloomreach Security Bulletin: log4j vulnerability

repository-data/application/src/main/resources/hcm-config/namespaces/hee/link.yaml
Hi @smanivasag / @adaMiclos,
I've made the field optional and have added a hint text.
Can you review please.
Thanks,
Raq
=> make new window field optional, add hint text

README.md, pom.xml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/forms.yaml
Hi @adaMiclos / @smanivasag - This PR updates to 14.7.3.
Can you review please?
Thanks,
Raq
=> update to version 14.7.3

repository-data/application/src/main/resources/hcm-config/namespaces/hee/link.yaml
Hi @smanivasag - making checkbox mandatory due to button appearing in cms ui when optional.
=> make checkbox mandatory as was adding button in cms ui

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/hometodentaltraineerecruitment.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/dental/landing-pages.yaml, repository-data/site-development/src/main/resources/hcm-content/hst/configurations/dental/workspace/pages/dental-trainee-recruitment-contentpage.yaml, repository-data/site-development/src/main/resources/hcm-content/hst/configurations/dental/workspace/sitemap/dental-trainee-recruitment.yaml
Hi @sankar-shunmuga - can you give this a review also please.
=> dental home redirect

repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml
Hi @smanivasag - this should be ready for review.
=> remove auth properties for prd dental

repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
=> feature/NWPS-847-RemoveExtraHEEComponent - removed extra comma

repository-data/application/src/main/resources/hcm-config/configuration/domains/content-website-testing-assets-and-gallery-readwrite.yaml, repository-data/application/src/main/resources/hcm-config/configuration/domains/content-website-testing.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/website-testing-author.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/website-testing-editor.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/website-testing-viewer.yaml, repository-data/application/src/main/resources/hcm-content/content/assets/website-testing.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/website-testing.yaml, repository-data/application/src/main/resources/hcm-content/content/gallery/website-testing.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/website-testing/home.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/components.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace/channel.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/tst-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/website-testing/workspace/channel/channelinfo.yaml, repository-data/site/src/main/resources/hcm-content/hst/sites/website-testing.yaml
hi @Raq-HEE , @adaMiclos, @dawntaroni 
Please review this
=> NWPS-851 - Website Testing Channel Creation - initial commit

repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-YellowAlertBlock-document.yaml, repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-YellowAlertBlock-folder.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd, repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/YellowAlertBlock.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/yellowAlertBlockReference.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/listing-pages.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/minihubs.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/site-banner.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/yellow-alert-block.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/Button.java, site/components/src/main/java/uk/nhs/hee/web/beans/YellowAlertBlock.java, site/components/src/main/java/uk/nhs/hee/web/beans/YellowAlertBlockReference.java
Hi @Raq-HEE , @adaMiclos , @dawntaroni 
Please review this.
NWPS-835-Reusable version of warning callout component
=> NWPS-835-Reusable version of warning callout component

repository-data/application/src/main/resources/hcm-config/namespaces/hee/caseStudy.yaml
Hi San - added a dummy commit to fix issues we're seeing on dev.
=> dummy commit to fix dev issues

repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-warningCallout-document.yaml, repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-warningCallout-folder.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd, repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/warningCallout.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/warningCalloutReference.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/components.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/warning-callout.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/WarningCallout.java, site/components/src/main/java/uk/nhs/hee/web/beans/WarningCalloutReference.java
=> redone warning callout without touching yellowalertblock

site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
Hi @sankar-shunmuga / @adaMiclos - can you please review this.
=> NWPS-881 - add news and blog categories to all channels

.github/workflows/cicd-release.yml, .github/workflows/cicd.yml, README.md
Hi @adaMiclos , updated the ci/cd pipeline github references . They are now pointing towards HEE
=> NWPS-883 Update CI/CD Github references from Manifesto to HEE

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/caseStudy.yaml
=> Bug-fix NWPS-877-879 - CaseStudy provider name change and warning callout name change

repository-data/application/src/main/resources/hcm-content/content/documents/lks/components.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/common/xpages.yaml, site/components/src/main/java/uk/nhs/hee/web/components/BlogPostComponent.java, site/components/src/main/java/uk/nhs/hee/web/eforms/hst/behaviors/BlogPostCommentMailFormDataBehavior.java, site/components/src/main/java/uk/nhs/hee/web/eforms/hst/behaviors/StoreBlogCommentBehavior.java
https://hee-tis.atlassian.net/browse/NWPS-401 
I have created a Blogpost experience page that contains a blogpost document and the blogpost form.
=> NWPS-401 Blog page layout (experience pages)

.github/workflows/cicd-release.yml, .github/workflows/cicd.yml
=> NWPS-900-Security Fixes

repository-data/application/src/main/resources/hcm-config/namespaces/hee/person.yaml, site/components/src/main/java/uk/nhs/hee/web/components/BlogPostComponent.java
https://hee-tis.atlassian.net/browse/NWPS-916
* Fix blogPostComponent to set valueLists required by the page content blocks
* Remove maxLength restriction for the bio field inside the Person document type
=> NWPS-916 Contact components are not displayed in blogPost pages

repository-data/application/src/main/resources/hcm-config/namespaces/hee/caseStudy.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/listingPage.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/listing.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/case-studies.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/casestudylisting-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/CaseStudy.java, site/components/src/main/java/uk/nhs/hee/web/components/ListingPageComponent.java, site/components/src/main/java/uk/nhs/hee/web/components/ListingPageType.java, site/components/src/main/java/uk/nhs/hee/web/repository/HEEField.java, site/components/src/test/java/uk/nhs/hee/web/components/ListingPageTypeTest.java
=> NWPS- 334 Case study submitted date

repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/stg-brcloud/io.yaml
=> NWPS-926-Preview unpublished documents

repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/io.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-brcloud/uk.yaml
=> NWPS-926 Preview unpublish documents Extension - Mapping with production DNS 

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/digital-transformation/logicmodelreportpdfredirect.yaml
=> NWPS-882- Redirect URL on Digital Transformation for Logic Model page

repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/medical.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/medical/medical-trainee-recruitment.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/hometomedicaltraineerecruitment.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/searchtosearchresultsredirect.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/medical/workspace/pages/medical-trainee-recruitment-contentpage.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/medical/workspace/sitemap/medical-trainee-recruitment.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/medical/workspace/sitemenus/main/Medical.yaml
=> NWPS-950 Redirect homepage to Medical-Trainee-Recruitment

repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-cookies-banner.ftl
=> NWPS-956 Disable JavaScript broken page fix

repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/lks/casestudyproviders.yaml
=> NWPS-917 Updated CaseStudyProviders Valuelists

repository-data/application/src/main/resources/hcm-config/configuration/update/registry/UpdateHippoDocbaseValuesToUUID.yaml
=> NWPS-979-Excessive Application Logs Issue fix

LICENSE
Added MIT licence for main repo
=> NWPS-978 - Create MIT LICENSE

repository-data/application/src/main/resources/hcm-config/namespaces/hee/banner.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/site-banner.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-banner.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/Banner.java, site/components/src/main/java/uk/nhs/hee/web/beans/HomePage.java
=> NWPS-297-Site-Promotion-Banner-Additional-Tag

repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/landingPage.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/landing-pages.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/landingPage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl, site/components/src/main/java/uk/nhs/hee/web/components/LandingPageComponent.java
Add the component in Landing Pages and Standard Content Pages types.
=> NWPS-991-add-navigation-map-to-other-content-types

repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-banner.ftl
=> NWPS-1005-Application-Log-Issue-Freemarker-Servlet-Logging

repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/landingPage.yaml
Remove Nav Map component from other content Types
=> NWPS-991 Remove Nav Map

repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
=> NWPS-1034-Report-Document-Type-Label-Change

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/guidance-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/cta-card.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/image-with-caption.ftl
=> NWPS-1018-bugfix/nwps-1018-Production-Issue-Logging

repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
=> NWPS-1034-Report-Label-Change-On-Catalog

repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/homepage-main.ftl
=> NWPS-1083-Homepage-Components-Working-Fix

repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
=> NWPS-1084-Top-Banner-For-Queen-Content-Change

repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
=> NWPS-1095-Remove-Banner-For-Queen

repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-menu.ftl
=> NWPS-1086-Chevron-Menu-Click-Scrolls-To-Top

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/block-links.ftl, repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
=> NWPS-1187-Page-Metadata-bugfix-resolving-null-values-entry

repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/Department.java
Reverting removal of `description` field for `Department` document type and its associated changes.
Note that this is branched out from `enhancement/nwps-1089-department-content-type`.
=> NWPS-1250: Department content model update for release version 1

repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/Department.java
Please review it . This needs to be merged with master once all other dependent tickets are ready like Person, Author, Contact Card and related migration groovy scripts
*Note:* UK country code (`+44`) validation for the `Phone number` field has been handled separately under https://github.com/Health-Education-England/hee-cms-platform/pull/281 PR.
=> NWPS-1089 - Department Content Type - Enhancement

repository-data/application/src/main/resources/hcm-config/configuration/update/registry/MigratePersonPronouns.yaml, repository-data/application/src/main/resources/hcm-config/configuration/update/registry/UpdateTwitterwithLinkUrl.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-contact.ftl
1. Updated person-contant.ftl to reflect FE design https://www.figma.com/file/QWKMNPz4dJxmzi47UB9pRF/3.-Content-Block-Library?node-id=530%3A748&t=NKfyQA7C1v3sxlOP-0
2. Created UpdateTwitterwithLinkUrl on registry to extract values from linkUrl to Twitter property
3. Updated existing contents in common folders
Please review this.
=> NWPS-1088-Person-Content-Type-Design-Updates

cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryPublicationProfessionsOrTopicsValidator.java, cms/src/main/java/uk/nhs/hee/web/validation/validator/NumericValidator.java, repository-data/application/src/main/resources/hcm-actions.yaml, repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtopics.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtypes.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
- Publication page
- 60 chars max length validation for `title` field.
- 'pageLastNextReview' field change as optional.
- `pageLastNextReview` field hint update.
- Publication landing page
- Numeric validation for `readTime` field.
- `publicationProfessions` & `publicationTopics` fields change as optional.
- `publicationProfessions` field move above `publicationTopics`.
- `updatedDate` field change as mandatory.
- Mandatory validation for publication professions/topics.
- Additional publication types inclusion:
- Business Plan
- Framework
- Review
- Additional publication topics inclusion:
- Advanced clinical practice
- Antimicrobial resistance
- Covid-19
- End of life care
- Health inequalities
- Infection management
- Neonatal
- Sexual and reproductive health
- Urgent and Emergency Care …
=> NWPS-1276: Publication and Publication landing page content model and template updates

repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
From some observations during testing we made the following changes:
-Change Hint in the ReadTime field in the CMS
-Show the 0KB for empty files for consistency
-UpdateDate filed now it is a optional value for the content editors to fill, there fore handle this in the ftl file in case it is missing.
=> NWPS-1276-be-changes-to-the-publication-pages

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
@smanivasag , it is work in progress. I would like you to review this changes on free marker files. 
If agreed, then we can apply for publication listing.
=> NWPS-1257-Search Feature results bugfix

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain_with_preview.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain_with_preview.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/hometodentaltraineerecruitment.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/searchtosearchresultsredirect.yaml
@smanivasag , please review this request. I have created four xml rule documents
1. Dental_Recruitment_Redirects_bloomreach_domain
2. Dental_Recruitment_Redirects_bloomreach_domain_with_preview
3. Dental_Recruitment_Redirects_hee_nhs_uk_domain
4. Dental_Recruitment_Redirects_hee_nhs_uk_domain_with_preview
=> NWPS-1250 Dental Recruitment Redirects

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/file-links-card.ftl
Please review it . 
Example: [https://dental.hee.nhs.uk/dental-trainee-recruitment/complaints]
=> NWPS-1161 Bugfix removing text opens in new window on free marker files

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
Reverts Health-Education-England/hee-cms-platform#318
It is subject to sign-off outcome.
=> Revert "NWPS-1257-Search Feature results bugfix"

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain_with_preview.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain_with_preview.yaml
Please review this. 
There are changes to url redirects
=> NWPS-1280 Dental recruitment redirect url changes

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl, site/components/src/main/java/uk/nhs/hee/web/components/ReportComponent.java
- Remove read-time info
- Split information into Publication type, Professions and Topics
=> NWPS-1347-BE-Right-side-Publication-Info-box-for-Publication-Single-Page

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl, site/components/src/main/java/uk/nhs/hee/web/components/PublicationLandingPageComponent.java, site/components/src/main/java/uk/nhs/hee/web/components/ReportComponent.java
Please review this.
Updated the following files 
repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
site/components/src/main/java/uk/nhs/hee/web/components/PublicationLandingPageComponent.java
repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
=> NWPS-1160 Publication Info Box for Publication Landing Page

cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueAuthorValidator.java, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
Improvement to Author by Person XPath query to search within the current channel only.
=> NWPS-1092: Author by Person XPath query Improvement

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/newsletter-subscribe-form.ftl
=> [NWPS-922] Adding text message next to recaptcha

repository-data/application/src/main/resources/hcm-config/namespaces/hee/author.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/Author.java
=> [NWPS-1368] Author: Change Bio to Text field

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
=> [NWPS-1274] Renaming Content Blocks

.github/workflows/cicd.yml
Updated the GitHub actions to separate development environment from workflow
Please review this ticket.
=> [NWPS-1234] Separating Development environment GitHub actions from workflow

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
=> [NWPS-1405] Author name not captured on search results bugfix

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
=> [NWPS-1274] Content block name changes

repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost-docker.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost-docker/internal.yaml
=> [NWPS-1234] Separating docker virtual localhost

repository-data/application/src/main/resources/hcm-config/namespaces/hee/contactCardWithDescription.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/contactCardWithDescriptionReference.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/listing-pages.yaml
This will correct the defects that Geraldine found during testing of this ticket.
1. Description text can be max 300 chars now
2. CMS Text now modified to indicate requirement for Person or Department
3. Person OR Department MUST be added to the card as that field is now mandatory
4. Text now changed in RHS when card is used
=> [NWPS-1090] Defect fix for contact card with description

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
=> [NWPS-1411-1424-1425-1427] Adding compounds to Content Blocks - News & Blogs

repository-data/application/src/main/resources/hcm-config/namespaces/hee/tabs.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/tabs.ftl
Title in [Content] [main] Tabs has been change to optional
=> NWPS-1404-Remove-mandatory-title-from-tabs-component

repository-data/application/src/main/resources/hcm-config/configuration/domains/content-wte-alpha-assets-and-gallery-readwrite.yaml, repository-data/application/src/main/resources/hcm-config/configuration/domains/content-wte-alpha.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/wte-alpha-author.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/wte-alpha-editor.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/wte-alpha-viewer.yaml, repository-data/application/src/main/resources/hcm-content/content/assets/wte-alpha.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/wte-alpha.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/wte-alpha/settings.yaml, repository-data/application/src/main/resources/hcm-content/content/gallery/wte-alpha.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/wte-alpha/home.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/components.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace/channel.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/br-cloud/cloud.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/wte-alpha/workspace/channel/channelinfo.yaml, repository-data/site/src/main/resources/hcm-content/hst/sites/wte-alpha.yaml, site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
Creation of New channel 'WTE Alpha'
=> NWPS-1499-Create-new-channel-to-support-alpha-project

repository-data/application/src/main/resources/hcm-config/configuration/domains/content-feedback-assets-and-gallery-readwrite.yaml, repository-data/application/src/main/resources/hcm-config/configuration/domains/content-feedback.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/feedback-author.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/feedback-editor.yaml, repository-data/application/src/main/resources/hcm-config/configuration/groups/feedback-viewer.yaml, repository-data/application/src/main/resources/hcm-config/configuration/userroles/hee.feedback.site.viewer.yaml, repository-data/application/src/main/resources/hcm-content/content/assets/feedback.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/feedback.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/feedback/settings.yaml, repository-data/application/src/main/resources/hcm-content/content/gallery/feedback.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/feedback/home.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/components.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace/channel.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace/pages.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace/sitemap.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/br-cloud/cloud.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost-docker/internal.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live/uk.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/feedback/workspace/channel/channelinfo.yaml, repository-data/site/src/main/resources/hcm-content/hst/sites/feedback.yaml
Added a new user role `hee.feedback.site.viewer` and configured it on `/hst:hee/hst:hosts/prd-live/uk/nhs/hee/feedback/hst:root` mount to let only participants of `Feedback` channel access the channel pages.
=> [NWPS-1291] Feedback (user research) channel build

cms-dependencies/pom.xml, pom.xml
Please review this commit. Enabled the plugin on both pom files
=> [NWPS-939] Text find replace plugin 

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
=> [NWPS-1402] Renamed remaining content blocks

repository-data/application/src/main/resources/hcm-actions.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/lks/casestudysectors.yaml
=> [NWPS-1478] Case Study Sectors values list updates

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/digital-transformation/philipsivesreviewpages.yaml
=> [NWPS-1516] Url redirects for Ives review pages - Digital Transformation

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-pages.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/training-home-contentpage.yaml, repository-data/site/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/training-home.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammesHomePage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammesHomepage.java, site/components/src/main/java/uk/nhs/hee/web/components/TrainingProgrammesHomepageComponent.java, site/components/src/main/java/uk/nhs/hee/web/components/info/MultiOrgLogoComponentInfo.java
1) Change the translation name to [Page] Training Homepage
2) Change the Caption path name to 'caption' for it to be rendered in the freemarker 
3) Change the Page to a 2 columns page (Main and Right Hand Components) 
4) Make 'Hero Image' required
5) Change the summary maximum length to 185 characters to avoid the overlap in the breadcrumb 
6) In Support Content blocks - add ActionLink to be rendered in the freemarker template 
7) Add the Right Hand Content Blocks to be rendered
=> NWPS-1488-BE-Updates-for-Training-Programme-Homepage

repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
Change page title limit to 120 characters
Change hint on page title as indicated in specs
=> NWPS-1506-BE-Publication-landing-page-Page-title-length

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
Rename: [Content Block][Main] Text to [Content Block][Main] Text block
=> [NWPS-1423] BE-Renaming-Text-to-Text-block

repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
Update the blogpost-main.ftl file to render the warning callout component
=> NWPS-1588-BE-Blog-post-Warning-callout-is-not-rendered

repository-data/application/src/main/resources/hcm-actions.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtopics.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
additions and updates for Topics value list on the CMS
=> [NWPS-1513] Publication-topics-Add-and-change-topics

repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/assetResource.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java, site/components/src/main/java/uk/nhs/hee/web/beans/Report.java
Small changes as follows;-
- Added otherFormats field for capture of email for Other Formats text
- Added Other formats text to template and also render otherFormats field contents
- Addressed issue w.r.t being able to select non assets for pother format of reports. You can still navigate away from assets but cannot select anything other than an asset
- Added a translation label for the 'Add' button for those assets (was previously showing 'assetResource')
=> [NWPS-1503] Publication landing page other format text on page

repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml, site/components/src/main/java/uk/nhs/hee/web/beans/Report.java, site/components/src/main/java/uk/nhs/hee/web/beans/StatementBlock.java, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammesHomepage.java, site/components/src/main/java/uk/nhs/hee/web/beans/YellowAlertBlock.java
Also, added a housekeeping commit c590a1baef2af43d6502f015a22c4fde7d6026a6.
=> [NWPS-1409] Removing uncommitted `Training homepage` document type nodes and tidy-up

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammesHomePage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/homepage-main.ftl
Note: Replacing `has-microhero` with `has-nhsukhero` for completeness
=> [NWPS-1530] Integration of FE styling fix for training home page hero summary overlapping issue

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
Take the main title and summary out of the Training journey box
=> NWPS-1522 BE: Work for the new Training Journey box

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
Change 'I' in Publication Info for lower case 'i'
=> NWPS-1576-Publication-Publication-info

repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml
=> NWPS-1563-be-training-programmes-homepage-outstanding-updates

repository-data/application/src/main/resources/hcm-config/namespaces/hee/tabPanel.yaml
=> NWPS-1579-H1-headings-in-tabs-component

repository-data/application/src/main/resources/hcm-config/namespaces/hee/imagesetWithCaption.yaml
Change label 'Description' to 'Alt text'
=> NWPS-1549-BE-Image-resource-Change-label-name-Description-to-Alt-text-

repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-document.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
Remove Right Hand Image from the Right hand content blocks
=> NWPS-1550-BE-Decommission-Image-re-usable-content-block-

repository-data/application/src/main/resources/hcm-config/configuration/workflows/gallery.yaml
=> NWPS-1547-Investigate-Image-resource-Stop-bulk-upload

repository-data/application/src/main/resources/hcm-config/namespaces/hee/assetResource.yaml
Change Publication date of assets below Title
=> NWPS-1559-be-publication-landing-page-language-and-doc-version

cms/src/main/java/uk/nhs/hee/web/validation/validator/AbstractMandatoryCombinationValidator.java, cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryPublicationProfessionsOrTopicsValidator.java, cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryTrainingProgrammeProfessionsOrTopicsValidator.java, repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml, repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-trainingProgrammePage-folder.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammePage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/medical.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/training-clinical-discipline.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/training-profession.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/training-recruitment-format.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/training-topic.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/training-type.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/lks/training-programmes-pages.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/minihubs.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-pages.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-programmes-pages.yaml, repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/training-program-page-contentpage.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammesHomepage.java, site/components/src/main/java/uk/nhs/hee/web/components/Model.java, site/components/src/main/java/uk/nhs/hee/web/components/TrainingProgrammePageComponent.java, site/components/src/main/java/uk/nhs/hee/web/repository/ValueListIdentifier.java, site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
This work is now featured in a new branch (after I mistakenly named the branch incorrectly)
=> Nwps 1523 do be work for training summary main content area

repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
Add inset text to Blogpost and News Articles
=> NWPS-1507-BE-Inset-text-on-news-articles-and-blog-posts

repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
Increase character limit in the Title of publication pages to 120
=> NWPS-1643-BE-Publication-page-Page-title-length

repository-data/site/src/main/resources/hcm-config/hst/blueprints/website-blueprint/configuration.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/pagenotfound.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/dental/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/digital-transformation/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/health-careers/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/kls/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/quality/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace.yaml, repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
Reverts Health-Education-England/hee-cms-platform#483
=> Revert "[NWPS-1662] Removal of the unused `pagenotfound` container"

cms/src/main/resources/ckeditor/styles_without_h1-h2.js, cms/src/main/resources/ckeditor/styles_without_h1.js, repository-data/application/src/main/resources/hcm-config/namespaces/hee/tabPanel.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hippostd/html.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-pages.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammesHomePage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammesHomepage.java
Replaces #482
- Replaces the `Summary` `Text` (area) field with a `Subtitle` `String` (i.e. text box) field with 120 characters limit.
- Replaces the `Caption` `Text` (area) field with a `Programme description` `Text` (area) field.
- Removes `Heading 1` & `Heading 2` styles from `Overview` RichText field.
=> [NWPS-1637] [WIP] Training home page updates

repository-data/application/src/main/resources/hcm-config/namespaces/hee/person.yaml
Make the person Title not required
=> NWPS-1519-Make-the-title-field-in-the-person-component-optional

repository-data/application/src/main/resources/hcm-actions.yaml, repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml, repository-data/application/src/main/resources/hcm-content/taxonomies.yaml
- `GlobalProfessions` taxonomy correction for `Ambulance service team`.
- `hee:mandatory-publication-professions-or-topics-validator` validation msg update.
=> [NWPS-1678] `GlobalProfessions` taxonomy correction and validation msg update

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/last-next-reviewed-date.ftl
Change to the new classes for 'application button' and take the new style.
Add setBundle to map the Message key with the label to render
=> NWPS-1589-FE-Training-programme-page-display-updates

repository-data/application/src/main/resources/hcm-content/taxonomies.yaml
Re-order taxonomy data to ensure it is added correctly
=> Nwps 1575 set up a way to link content blocks on training page

repository-data/application/src/main/resources/hcm-actions.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammePage.yaml, repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/training-type.yaml, repository-data/application/src/main/resources/hcm-content/taxonomies.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-programmes-pages.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java, site/components/src/main/java/uk/nhs/hee/web/components/TrainingProgrammePageComponent.java, site/components/src/main/java/uk/nhs/hee/web/constants/HEETaxonomy.java, site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
Updates according to testing;-
- Added correct hints for professions and topics as per spec
- Added recruitment format taxonomy as this was missing and cause N/A option to be unavailable
- clarified (in ticket comments) behaviour of numeric fields
=> [NWPS-1523] Include recruitment format and other taxonomies for TPP

repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammePage.yaml, repository-data/application/src/main/resources/hcm-content/taxonomies.yaml, repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/training-programme-page.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java, site/components/src/main/java/uk/nhs/hee/web/components/TrainingProgrammePageComponent.java, site/components/src/main/java/uk/nhs/hee/web/constants/HEETaxonomy.java
Change Clinical Discipline value list  to Global Clinical Discipline taxonomy
=> NWPS-1724-be-training-programme-taxonomy-updates

repository-data/application/src/main/resources/hcm-config/namespaces/hee/MiniHub.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/MiniHub.java
Add a new field, Summary, below Title
Character limit - 300
Hint - Enter summary (300 character limit)
=> NWPS-1681-BE-Mini-hub-Summary-field-work

repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/hometomedicaltraineerecruitment.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/specialtytrainingtomedicaltrainingredirects.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live-redirect/uk.yaml
The global content for medical specialty training on https://specialtytraining.hee.nhs.uk/ has been migrated to the NWP, 49 redirects rules were added
=> NWPS-1166-Redirect-Speciality-Training-To-Medical-Channel

repository-data/application/src/main/resources/hcm-config/namespaces/hee/MiniHub.yaml
Make the Summary field on the mini-hub optional (not required)
=> NWPS-1813-BE-Mini-hub-Change-Summary-field-to-be-optional

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-detail.ftl
1) Add Featured content block in SCP freemarker template
2)Modify news and blogs freemarker template to show Featured content after the author section
=> NWPS-1803-BE-Featured-content-fixes-and-improvements

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/quote.ftl
Added a visual hidden `h2` element with `Quote` text for accessibility
=> [NWPS-1814] Quote content block accessibility fix

repository-data/application/src/main/resources/hcm-content/taxonomies.yaml, site/components/src/main/java/uk/nhs/hee/web/constants/HEETaxonomy.java
=> NWPS-1796-BE-New-taxonomy-Regions-just-Column-A

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/google-map.ftl
Modify the freemarker for Google maps content block don't show if it is unpublished.
=> NWPS-1822-BE-Google-map-unpublished-displays-incorrectly

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/featured-content.ftl
Change the ‘Publish date’ label to ‘Published date’ so that all date fields are consistent,
=> NWPS-1828-BE-FE-Featured-content-cards-Update

repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml, repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml, repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl, repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl, site/components/src/main/java/uk/nhs/hee/web/beans/BlogPost.java, site/components/src/main/java/uk/nhs/hee/web/beans/News.java
- Amended `Featured content` as furniture on `Blog post` and `News article` pages.
- Removed `Featured content` content block from `Publication (single) page`.
=> [NWPS-1838] Featured content updates to Blog post, News article and Publication (single) pages

repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
Add Name title and job title to the accessible label for the screen reader include them
=> NWPS-1817-fe-accessibility-author-card

repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl, site/components/src/main/java/uk/nhs/hee/web/components/TrainingProgrammePageComponent.java
Put a condition in freemarker template to generate the default expanded Training programme summary if it is 'Overview' and if it is a SCP collapsed by default
=> NWPS-1763-FE-Training-programme-page-enhancements

.github/workflows/ci.yml, .github/workflows/cicd-release.yml, .github/workflows/cicd.yml
Reverts Health-Education-England/hee-cms-platform#642
=> Revert "[NWPS-1860] GitHub actions upgrade (to use of `Node.js 20` runtime version of the actions) on CI/CD pipeline"

repository-data/application/src/main/resources/hcm-actions.yaml, repository-data/application/src/main/resources/hcm-config/configuration/modules/urlrewriter.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls/kfhtolksredirects.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/gpnrotomedicalgpredirects.yaml, repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/specialtytrainingtomedicaltrainingredirects.yaml, repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live-redirect/uk.yaml
Reverts Health-Education-England/hee-cms-platform#620. This PR needs to be reverted as this is causing mis-redirection for authenticated pages
=> Revert "[NWPS-1849] Domain redirect support for requests with POST method"
